name: Moda config bundle
# Run this action on any pull request, push to the master branch
on:
  pull_request: {}
  push:
    branches:
      - master
      - enterprise-*.*-release

jobs:
  dependency-graph-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run some code
        run: |
          ruby puts "HIII"
