name: Moda config bundle
# Run this action on any pull request, push to the master branch
on:
  pull_request: {}
  push:
    branches:
      - master
      - enterprise-*.*-release

jobs:
  run-some-code-woot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run some code
        run: |
          ruby hi.rb
