name: Moda config bundle
# Run this action on any pull request, push to the master branch
on:
  push: {}

jobs:
  create_moda_config_bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run some code
        run: |
          ruby build_moda_config_bundle.rb
